### ISSUE TITLE
hotkeys.del is not working

### ISSUE THREAD

**Issue by huangp** [chieffancypants/angular-hotkeys#100]
Mousetrap.unbind expects two parameters whereas hotkeys._del method only give one(missing the action). Therefore the del function will not remove the hotkey callback effect (only removed it from cheatsheet). 

Using hotkeys 1.4.5 and mousetrap is on 1.4.6

**Comment by aaronsullivan** [comment]
+1. 

If I temporarily change the code to Moustrap.unbind(combo, action) then my shortcut combo gets correctly removed (not just from the cheatsheet).

**Comment by chieffancypants** [comment]
Sorry for the delay here, I'm trying to clean up old tickets. Hotkeys are normally deleted using the key combo 'mod+i', not the actual hotkey object.  If this does not fix your issue, please re-open

**Comment by mgm09a** [comment]
This is still an issue. It's impossible to unbind a non-keydown event. The plnkr shared concisely demonstrates it, and it's a quick modification to the example provided to show that passing 'mod+i' to the delete function instead of the hotkey object still doesn't resolve it. Would you be able to take another look at this? Seems like a minor change to your hotkeys.del() function to accept an optional second parameter to specify the action would do it.
