### ISSUE TITLE
Symbols in cheat sheet are broken

### ISSUE THREAD

**Issue by richtmat** [chieffancypants/angular-hotkeys#179]
Some symbols representing keys like 'up', 'down', etc are broken in my Linux/Electron app.

![screenshot from 2015-09-21 17 51 17](https://cloud.githubusercontent.com/assets/3274293/9996924/c9b0f00a-6089-11e5-8c09-4abb29e779f8.png)

Do I need to include anything beside hotkeys.css/js ?

**Comment by chieffancypants** [comment]
Hmm, nope, it's just using unicode for those characters.

**Comment by richtmat** [comment]
So what is possibly wrong here? I can display those characters anywhere else on the app and its fine.

**Comment by chieffancypants** [comment]
Really hard for me to say without access to the project you're working on.  There are too many situations where this could have been broken downstream of the provided built files.  For example, did you build hotkeys yourself or attempt to minify it or otherwise process it in a way that could strip the unicode?  Perhaps the file was not (at one point or another) stored in UTF-8 format?

Another thing you could try would be replacing the actual unicode characters (such as ⌘) with their escape sequences (⌘ becomes `\u2318`) in the source, which may prevent inadvertent downstream tampering.

**Comment by richtmat** [comment]
I get via bower and include the hotkeys.css/.js unminified. The app is unminified as well.

The escaped sequence works for me! That is ok as a workaround but I would like to solve that properly.

The file is encoded in UTF-8 though:

```$ file bower_components/angular-hotkeys/build/hotkeys.js
bower_components/angular-hotkeys/build/hotkeys.js: HTML document, UTF-8 Unicode text```

**Comment by chieffancypants** [comment]
If you want to submit a PR, I'm ok with using escape sequences as long as those escape sequences contain comments with the actual unicode (to avoid having to look things up later).

**Comment by richtmat** [comment]
There it is: https://github.com/chieffancypants/angular-hotkeys/pull/181
